// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vividbridge/vividbridge/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc50ce7fa95353b0, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc50ce7fa95353b0, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetVividGuardiansRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetVividGuardiansRequest) Reset()         { *m = QueryGetVividGuardiansRequest{} }
func (m *QueryGetVividGuardiansRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetVividGuardiansRequest) ProtoMessage()    {}
func (*QueryGetVividGuardiansRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc50ce7fa95353b0, []int{2}
}
func (m *QueryGetVividGuardiansRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVividGuardiansRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVividGuardiansRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVividGuardiansRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVividGuardiansRequest.Merge(m, src)
}
func (m *QueryGetVividGuardiansRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVividGuardiansRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVividGuardiansRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVividGuardiansRequest proto.InternalMessageInfo

func (m *QueryGetVividGuardiansRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetVividGuardiansResponse struct {
	VividGuardians VividGuardians `protobuf:"bytes,1,opt,name=VividGuardians,proto3" json:"VividGuardians"`
}

func (m *QueryGetVividGuardiansResponse) Reset()         { *m = QueryGetVividGuardiansResponse{} }
func (m *QueryGetVividGuardiansResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetVividGuardiansResponse) ProtoMessage()    {}
func (*QueryGetVividGuardiansResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc50ce7fa95353b0, []int{3}
}
func (m *QueryGetVividGuardiansResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVividGuardiansResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVividGuardiansResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVividGuardiansResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVividGuardiansResponse.Merge(m, src)
}
func (m *QueryGetVividGuardiansResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVividGuardiansResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVividGuardiansResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVividGuardiansResponse proto.InternalMessageInfo

func (m *QueryGetVividGuardiansResponse) GetVividGuardians() VividGuardians {
	if m != nil {
		return m.VividGuardians
	}
	return VividGuardians{}
}

type QueryAllVividGuardiansRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVividGuardiansRequest) Reset()         { *m = QueryAllVividGuardiansRequest{} }
func (m *QueryAllVividGuardiansRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllVividGuardiansRequest) ProtoMessage()    {}
func (*QueryAllVividGuardiansRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc50ce7fa95353b0, []int{4}
}
func (m *QueryAllVividGuardiansRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVividGuardiansRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVividGuardiansRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVividGuardiansRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVividGuardiansRequest.Merge(m, src)
}
func (m *QueryAllVividGuardiansRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVividGuardiansRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVividGuardiansRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVividGuardiansRequest proto.InternalMessageInfo

func (m *QueryAllVividGuardiansRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllVividGuardiansResponse struct {
	VividGuardians []VividGuardians    `protobuf:"bytes,1,rep,name=VividGuardians,proto3" json:"VividGuardians"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVividGuardiansResponse) Reset()         { *m = QueryAllVividGuardiansResponse{} }
func (m *QueryAllVividGuardiansResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllVividGuardiansResponse) ProtoMessage()    {}
func (*QueryAllVividGuardiansResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc50ce7fa95353b0, []int{5}
}
func (m *QueryAllVividGuardiansResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVividGuardiansResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVividGuardiansResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVividGuardiansResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVividGuardiansResponse.Merge(m, src)
}
func (m *QueryAllVividGuardiansResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVividGuardiansResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVividGuardiansResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVividGuardiansResponse proto.InternalMessageInfo

func (m *QueryAllVividGuardiansResponse) GetVividGuardians() []VividGuardians {
	if m != nil {
		return m.VividGuardians
	}
	return nil
}

func (m *QueryAllVividGuardiansResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "vividbridge.vividbridge.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "vividbridge.vividbridge.QueryParamsResponse")
	proto.RegisterType((*QueryGetVividGuardiansRequest)(nil), "vividbridge.vividbridge.QueryGetVividGuardiansRequest")
	proto.RegisterType((*QueryGetVividGuardiansResponse)(nil), "vividbridge.vividbridge.QueryGetVividGuardiansResponse")
	proto.RegisterType((*QueryAllVividGuardiansRequest)(nil), "vividbridge.vividbridge.QueryAllVividGuardiansRequest")
	proto.RegisterType((*QueryAllVividGuardiansResponse)(nil), "vividbridge.vividbridge.QueryAllVividGuardiansResponse")
}

func init() {
	proto.RegisterFile("vividbridge/vividbridge/query.proto", fileDescriptor_fc50ce7fa95353b0)
}

var fileDescriptor_fc50ce7fa95353b0 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xc1, 0x6b, 0x14, 0x31,
	0x14, 0xc6, 0x37, 0xe3, 0xba, 0x87, 0x08, 0x05, 0x63, 0x41, 0x19, 0x74, 0xba, 0x44, 0xd1, 0x6a,
	0x6d, 0xe2, 0x56, 0xa8, 0x20, 0x78, 0x68, 0x0f, 0xee, 0xb5, 0x0e, 0xea, 0xc1, 0x8b, 0x64, 0x9c,
	0x10, 0x02, 0xd3, 0xc9, 0x74, 0x32, 0xbb, 0x5a, 0xc4, 0x8b, 0xf7, 0x82, 0xe0, 0x1f, 0x23, 0xde,
	0x3c, 0xf6, 0x58, 0xf0, 0xe2, 0x49, 0x64, 0xd7, 0x3f, 0x44, 0x26, 0xc9, 0xe2, 0xcc, 0xda, 0x74,
	0x57, 0x7a, 0x0b, 0x9b, 0xef, 0x7d, 0xdf, 0xef, 0xe5, 0xbd, 0x59, 0x78, 0x73, 0x2c, 0xc7, 0x32,
	0x4d, 0x4a, 0x99, 0x0a, 0x4e, 0x9b, 0xe7, 0x83, 0x11, 0x2f, 0x0f, 0x49, 0x51, 0xaa, 0x4a, 0xa1,
	0xab, 0x8d, 0x0b, 0xd2, 0x38, 0x87, 0xab, 0x42, 0x09, 0x65, 0x34, 0xb4, 0x3e, 0x59, 0x79, 0x78,
	0x5d, 0x28, 0x25, 0x32, 0x4e, 0x59, 0x21, 0x29, 0xcb, 0x73, 0x55, 0xb1, 0x4a, 0xaa, 0x5c, 0xbb,
	0xdb, 0x7b, 0x6f, 0x94, 0xde, 0x57, 0x9a, 0x26, 0x4c, 0xbb, 0x14, 0x3a, 0x1e, 0x24, 0xbc, 0x62,
	0x03, 0x5a, 0x30, 0x21, 0x73, 0x23, 0x76, 0xda, 0x5b, 0x3e, 0xba, 0x82, 0x95, 0x6c, 0x7f, 0xe6,
	0xb8, 0xe9, 0x53, 0x99, 0xf3, 0x6b, 0x31, 0x62, 0x65, 0x2a, 0xd9, 0x0c, 0x00, 0xaf, 0x42, 0xf4,
	0xac, 0x8e, 0xdd, 0x33, 0x1e, 0x31, 0x3f, 0x18, 0x71, 0x5d, 0xe1, 0xe7, 0xf0, 0x4a, 0xeb, 0x57,
	0x5d, 0xa8, 0x5c, 0x73, 0xf4, 0x04, 0xf6, 0x6c, 0xd6, 0x35, 0xd0, 0x07, 0xeb, 0x97, 0xb6, 0xd6,
	0x88, 0xe7, 0x2d, 0x88, 0x2d, 0xdc, 0xed, 0x1e, 0xff, 0x5c, 0xeb, 0xc4, 0xae, 0x08, 0x53, 0x78,
	0xc3, 0xb8, 0x0e, 0x79, 0xf5, 0xb2, 0xd6, 0x0e, 0x67, 0x2c, 0x2e, 0x16, 0xad, 0xc0, 0x40, 0xa6,
	0xc6, 0xbb, 0x1b, 0x07, 0x32, 0xc5, 0x6f, 0x61, 0xe4, 0x2b, 0x70, 0x44, 0x2f, 0xe0, 0x4a, 0xfb,
	0xc6, 0x91, 0xdd, 0xf1, 0x92, 0xb5, 0xe5, 0x8e, 0x70, 0xce, 0x04, 0x0b, 0x47, 0xba, 0x93, 0x65,
	0xa7, 0x93, 0x3e, 0x85, 0xf0, 0xef, 0x7c, 0x5c, 0xe6, 0x6d, 0x62, 0x87, 0x49, 0xea, 0x61, 0x12,
	0xbb, 0x32, 0x6e, 0x98, 0x64, 0x8f, 0x09, 0xee, 0x6a, 0xe3, 0x46, 0x25, 0xfe, 0x06, 0x5c, 0x8b,
	0xa7, 0x24, 0x9d, 0xd1, 0xe2, 0x85, 0x73, 0xb7, 0x88, 0x86, 0xad, 0x0e, 0x02, 0xf7, 0x6a, 0x8b,
	0x3a, 0xb0, 0x4c, 0xcd, 0x16, 0xb6, 0x8e, 0xba, 0xf0, 0xa2, 0x69, 0x01, 0x1d, 0x01, 0xd8, 0xb3,
	0x83, 0x47, 0x1b, 0x5e, 0xb8, 0x7f, 0xb7, 0x2d, 0xbc, 0xbf, 0x9c, 0xd8, 0x66, 0xe3, 0xf5, 0x8f,
	0xdf, 0x7f, 0x7f, 0x0e, 0x30, 0xea, 0xdb, 0x8d, 0xde, 0xf4, 0x7e, 0x10, 0xe8, 0x2b, 0x98, 0x7f,
	0x3a, 0xb4, 0x7d, 0x76, 0x94, 0x6f, 0x33, 0xc3, 0x47, 0xff, 0x5d, 0xe7, 0x68, 0xb7, 0x0d, 0xed,
	0x03, 0x44, 0xfc, 0xb4, 0x73, 0x1f, 0x26, 0x7d, 0x2f, 0xd3, 0x0f, 0xe8, 0x0b, 0x80, 0x97, 0xdb,
	0x96, 0x3b, 0x59, 0xb6, 0x08, 0xdf, 0xb7, 0xae, 0x8b, 0xf0, 0xbd, 0xcb, 0x87, 0x07, 0x06, 0x7f,
	0x03, 0xdd, 0x5d, 0x1a, 0x7f, 0xf7, 0xf1, 0xf1, 0x24, 0x02, 0x27, 0x93, 0x08, 0xfc, 0x9a, 0x44,
	0xe0, 0xd3, 0x34, 0xea, 0x9c, 0x4c, 0xa3, 0xce, 0x8f, 0x69, 0xd4, 0x79, 0xd5, 0x6f, 0x79, 0xbc,
	0x6b, 0xb9, 0x54, 0x87, 0x05, 0xd7, 0x49, 0xcf, 0xfc, 0x29, 0x3d, 0xfc, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x89, 0xdd, 0xb0, 0x99, 0x89, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a VividGuardians by id.
	VividGuardians(ctx context.Context, in *QueryGetVividGuardiansRequest, opts ...grpc.CallOption) (*QueryGetVividGuardiansResponse, error)
	// Queries a list of VividGuardians items.
	VividGuardiansAll(ctx context.Context, in *QueryAllVividGuardiansRequest, opts ...grpc.CallOption) (*QueryAllVividGuardiansResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/vividbridge.vividbridge.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VividGuardians(ctx context.Context, in *QueryGetVividGuardiansRequest, opts ...grpc.CallOption) (*QueryGetVividGuardiansResponse, error) {
	out := new(QueryGetVividGuardiansResponse)
	err := c.cc.Invoke(ctx, "/vividbridge.vividbridge.Query/VividGuardians", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VividGuardiansAll(ctx context.Context, in *QueryAllVividGuardiansRequest, opts ...grpc.CallOption) (*QueryAllVividGuardiansResponse, error) {
	out := new(QueryAllVividGuardiansResponse)
	err := c.cc.Invoke(ctx, "/vividbridge.vividbridge.Query/VividGuardiansAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a VividGuardians by id.
	VividGuardians(context.Context, *QueryGetVividGuardiansRequest) (*QueryGetVividGuardiansResponse, error)
	// Queries a list of VividGuardians items.
	VividGuardiansAll(context.Context, *QueryAllVividGuardiansRequest) (*QueryAllVividGuardiansResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) VividGuardians(ctx context.Context, req *QueryGetVividGuardiansRequest) (*QueryGetVividGuardiansResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VividGuardians not implemented")
}
func (*UnimplementedQueryServer) VividGuardiansAll(ctx context.Context, req *QueryAllVividGuardiansRequest) (*QueryAllVividGuardiansResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VividGuardiansAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vividbridge.vividbridge.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VividGuardians_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVividGuardiansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VividGuardians(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vividbridge.vividbridge.Query/VividGuardians",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VividGuardians(ctx, req.(*QueryGetVividGuardiansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VividGuardiansAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllVividGuardiansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VividGuardiansAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vividbridge.vividbridge.Query/VividGuardiansAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VividGuardiansAll(ctx, req.(*QueryAllVividGuardiansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vividbridge.vividbridge.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "VividGuardians",
			Handler:    _Query_VividGuardians_Handler,
		},
		{
			MethodName: "VividGuardiansAll",
			Handler:    _Query_VividGuardiansAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vividbridge/vividbridge/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetVividGuardiansRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVividGuardiansRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVividGuardiansRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVividGuardiansResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVividGuardiansResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVividGuardiansResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.VividGuardians.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllVividGuardiansRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVividGuardiansRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVividGuardiansRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllVividGuardiansResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVividGuardiansResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVividGuardiansResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.VividGuardians) > 0 {
		for iNdEx := len(m.VividGuardians) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VividGuardians[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetVividGuardiansRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetVividGuardiansResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.VividGuardians.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllVividGuardiansRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllVividGuardiansResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.VividGuardians) > 0 {
		for _, e := range m.VividGuardians {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVividGuardiansRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVividGuardiansRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVividGuardiansRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVividGuardiansResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVividGuardiansResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVividGuardiansResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VividGuardians", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VividGuardians.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVividGuardiansRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVividGuardiansRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVividGuardiansRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVividGuardiansResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVividGuardiansResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVividGuardiansResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VividGuardians", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VividGuardians = append(m.VividGuardians, VividGuardians{})
			if err := m.VividGuardians[len(m.VividGuardians)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
